### ISSUE TITLE
Can't use mouse to navigate on signal with multiple navigation dimensions.

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#104]
I can't slide the red line left-right (or up-down) on the image attached. 
I'm not sure if this is intended behaviour or not, but I think not.

It would be nice to be able to move the red slider in all direction to show a different image in the signal plot, rather than rely on the arrow keys.

![screenshot 2017-01-31 15 23 40](https://cloud.githubusercontent.com/assets/2721423/22471111/527ccc20-e7c9-11e6-944c-9aa3fa432dbd.png)

**Comment by vidartf** [comment]
I'm confused about what steps would be required to reproduce this. Is this a 2D navigation? If so, isn't the issue simply a very distorted pixel box? If that is the case, I would say this is a hspy issue.

**Comment by thomasaarholt** [comment]
You're probably right. Just reporting errors as I'm seeing them, this week. Not enough time to test all. Good point though.

**Comment by vidartf** [comment]
OK, please reopen if you figure this was an issue with the UI after all.
