### ISSUE TITLE
Opening hyperspyui with multiple files from command line

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#106]
Sometimes code speaks clearer than words. I was expecting this to work, but this is all that happens:
```
hyperspyui file1.dm3 file2.dm3
INFO:hyperspy.io_plugins.bcf:The fast cython based bcf unpacking library were found
QLocalSocket::connectToServer: Connection refused
```

The same error happens when I already have hyperspyui open and try to open a file with the command `hyperspyui file3.dm3`. Opening one file on its own with hyperspyui closed is fine.

With the Mac OS app shortcut I'm making, I'm currently passing the above with single quotes, i.e. `hyperspyui 'file1.dm3' 'file2.dm3'`. This doesn't work either, but I haven't figured out how not to pass it with single quotes yet.

**Comment by vidartf** [comment]
Just to make sure:

 - With the UI closed:
   - `hyperspyui file1.dm3` works
   - `hyperspyui file1.dm3 file2.dm3` fails ?
 - With the UI open, both commands fail

**Comment by thomasaarholt** [comment]
Right. Having just restarted my computer, everything suddenly works. I'll see if I can spot the QLocalSocket error. 

So yeah, we essentially have a working Mac "app". Will keep testing for now though.

**Comment by vidartf** [comment]
Reopen if you spot this again. Until then, I'll write this of as [neutrinos](https://en.wikipedia.org/wiki/Faster-than-light_neutrino_anomaly) :)
