### ISSUE TITLE
Cropped signals lack a scale bar

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#109]
I don't particularly like the built-in scalebar in HS, but it's missing if one uses the GUI to crop a signal.

**Comment by vidartf** [comment]
Can reproduce, not sure if this is a bug with Hyperspy or how the UI uses hspy.

The code the UI uses to crop:
```python
slices = roi._make_slices(sig_axes, axes)
signal.data = signal.data[slices]
if roi.ndim > 0:
    signal.axes_manager[axes[0]].offset = roi.left
if roi.ndim > 1:
    signal.axes_manager[axes[1]].offset = roi.top

signal.squeeze()
signal.get_dimensions_from_data()
signal.events.data_changed.trigger(signal)
```

@hyperspy/developers  : Thoughts about why this would not give a scalebar?

**Comment by francisco-dlp** [comment]
The issue is that the scalebar position is not updated when updating the plot...hence it's a hspy bug. @thomasaarholt, could you submit it there?

**Comment by vidartf** [comment]
@thomasaarholt If you submitted to hspy, it would be nice if you linked the issue here for any others that are interested in this.

**Comment by thomasaarholt** [comment]
Yes, I forgot to link it. [Here is the issue](https://github.com/hyperspy/hyperspy/issues/1421). Not fixed at time of writing.
