### ISSUE TITLE
Pressing "L" on a plotted navigator window sets the y axis scale to log rather than intensity scale to log

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#111]
It would be nice to be able to press L and have the intensity go to log scale. The behaviour described above doesn't work properly, either.

**Comment by vidartf** [comment]
This functionality is actually from matplotlib (http://matplotlib.org/users/navigation_toolbar.html#navigation-keyboard-shortcuts). We could maybe override it?
