### ISSUE TITLE
Add HyperSpyUI to conda forge

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspyUI#132]
The next release of hyperspy in conda-forge won't install traitsui in order to avoid the issue with qt4 and, therefore, installing hyperspyui will be less straightforward. What about adding a conda recipe for hyperspyui that depends on traitsui and pyqt4? The time should be ripe for it now that hyperspyui comes with unittests.

**Comment by vidartf** [comment]
I have considered this before, but some of the UI's other dependencies are not available on conda yet, unfortunately. Off the top of my head, at least pyQode is not there (an auto project is there, but it is out-dated), and possibly also the PyQt/PySide helper (but that can be worked around).

**Comment by francisco-dlp** [comment]
qtpy is in conda-forge, is based on pyQode, and seems to be a more popular choice.

**Comment by vidartf** [comment]
Yes and no. QtPy is based on pyQode.qt, which is the Qt compatibility layer, and I agree that might be a better option than the current bindings (thanks!). However, the rest of the pyQode package is for having a Qt code/text editor with linting and tab-completion etc. If you know of a similar replacement for that, it would be really helpful :)

**Comment by francisco-dlp** [comment]
[qscintilla](https://github.com/conda-forge/qscintilla2-feedstock)?

**Comment by francisco-dlp** [comment]
An extra motivation to replace pyqode is that it is not in Debian either. Getting hyperspy in debian should be possible with v1.3 as it no longer depends on traitsui. It'll be awesome to get hyperspyui in Debian too.

**Comment by thomasaarholt** [comment]
Are user channels safe to use?
Pyqode on anaconda: 
https://anaconda.org/gbaty/pyqode.python

**Comment by jat255** [comment]
Revisiting this... it looks like the only dependent packages I can see that are not available through conda are:

```
pyqode.qt
pyqode.core
pyqode.python
```

As @thomasaarholt pointed out, these packages are available in a few different user channels: https://anaconda.org/search?q=pyqode

Can we use one of these ([tissuelab](https://anaconda.org/tissuelab/repo) looks the most used), or would it be worth the effort to get them included in conda-forge, so we can package the UI on there? I think that would go a long way towards user experience, if we could just say `conda install hyperspyui` and everything would be taken care of automatically.

**Comment by jat255** [comment]
Also, pyqode was abandoned in October of last year... https://github.com/pyQode/pyQode/issues/79

It might be worthwhile to explore switching to other options.

**Comment by jat255** [comment]
I'm glad I looked... looks like @ericpre beat me to the punch: https://github.com/conda-forge/staged-recipes/pull/6507

**Comment by ericpre** [comment]
It will be much easier to get pyqode in conda-forge than looking for alternative. pyqode works fine for hyperspyui and even if this is not maintained anymore, it should be working fine for a while.

**Comment by ericpre** [comment]
All dependencies should be in conda-forge now!

https://anaconda.org/search?q=platform%3Anoarch+pyqode

pyqode may get broken with new releases of its dependencies since it is currently not maintained anymore but at the moment it is still fine...

**Comment by jat255** [comment]
@ericpre since you're now the resident conda-forge expert, do you want to submit the recipe for HyperSpyUI, as well?

**Comment by ericpre** [comment]
See https://github.com/conda-forge/hyperspyui-feedstock
