### ISSUE TITLE
Installing using pip and conda on Windows (Step by Step)

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#146]
HyperspyUI is currently a bit difficult to install as it depends on PyQT4. 

I thought I'd leave here the method I just used to install HyperspyUI in a clean anaconda environment.
First I install python version 3.5 and numpy (hyperspyUI currently does not depend on numpy (?) and threw an error during my first install). Here I call the conda environment "UI", although you can call it want you want. You could also just install it in your default conda environment.

```bash
conda create --name UI python=3.5 numpy hyperspy
```

After creating the conda environment, we need to activate it:
`activate UI`

Now I install hyperspyUI from pip:

`pip install hyperspyui`

Finally install pyqt4 from a particular conda package owner:
`conda install -c menpo pyqt`

Done!

Check that it works by typing `python -m hyperspyui`. If there are no errors, just fire it up using just `hyperspyui` in the future!

**Comment by vidartf** [comment]
Thanks! Feel free to make a PR where you put this in README and/or docs :)
