### ISSUE TITLE
hyperspyUI problems with accessing the developer's folder 

### ISSUE THREAD

**Issue by jennywlANU** [hyperspy/hyperspyUI#169]
I am using a MacBookPro and have installed HyperSpy successfully. I would like to install the HyperSpy UI.

### Steps to reproduce

and if I use the command python -m hyperspyui as described in GitHub. I get the log pasted below

### Actual behavior
there is a problem accessing the files. Grateful for any suggestions, thanks.

bash-3.2$ pip install git+git://github.com/hyperspy/hyperspyUI.git
Collecting git+git://github.com/hyperspy/hyperspyUI.git
  Cloning git://github.com/hyperspy/hyperspyUI.git to /private/var/folders/hl/31ns6qwx531c1t7nqh7sxm2h0000gn/T/pip-req-build-gba82zcy
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Command "git clone -q git://github.com/hyperspy/hyperspyUI.git /private/var/folders/hl/31ns6qwx531c1t7nqh7sxm2h0000gn/T/pip-req-build-gba82zcy" failed with error code 1 in None

<img width="1280" alt="screen shot 2018-09-04 at 2 22 51 pm" src="https://user-images.githubusercontent.com/28881063/45010107-0a820c00-b04f-11e8-8c96-9afcb904426e.png">

**Comment by ericpre** [comment]
As workaround try to use:
```
pip install https://github.com/hyperspy/hyperspyUI/archive/master.zip
```
It seems that you have an issue with git on your system.

**Comment by ericpre** [comment]
Solved with new release.
