### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspyUI#173]
@vidartf: is there any blocker for a new release?
- qt5 migration, any more issues?
- progress bar?
- anything else?

A few installation issues has been reported (#159 and #169) which would be fixed with a new release and the creation of a conda-forge package.
We use the master branch since more than 6 months in the winpython bundle and it seems to work fine.

**Comment by vidartf** [comment]
It is probably reasonable with another release, I keep loosing the thread. Do you want to do the release? I can add you and some other hyperspy devs to the PyPI package.

**Comment by vidartf** [comment]
You should be added now, with the option to add others as appropriate.

**Comment by ericpre** [comment]
OK thanks! Do you want me to do the release on github too? If so, I would need the writing right to this repo.

**Comment by vidartf** [comment]
After transfering this repo to the hyperspy org, I don't seem to be listed as an owner anymore. You would need to ask the @hyperspy/owners for this.

**Comment by ericpre** [comment]
This needs fixing then! I will follow up with @francisco-dlp.

**Comment by francisco-dlp** [comment]
@vidartf, when you transferred the ownership of the project I forgot to give write access to the developer team. I've just fixed the issue.

**Comment by ericpre** [comment]
I will try to do a release in the next couple of days and package it on conda-forge once it is available on pypi.
There were quite a few changes in dependency requirements, so we may get an unexpected bug or installation issue, in which case, we may need to another quick release...
