### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by somboon39** [hyperspy/hyperspyUI#200]
Hello,

Can you help me with this error "**ValueError: negative dimensions are not allowed**"

![image](https://user-images.githubusercontent.com/84850133/123445023-137e6680-d60a-11eb-96f5-6b1bd2205325.png)
 that should normally be included in a new issue: ---

**Comment by ericpre** [comment]
Similarly as https://github.com/hyperspy/hyperspy/issues/2776, from the error traceback, this is an atomap issue and this needs to be ask at https://gitlab.com/atomap/atomap/-/issues
