### ISSUE TITLE
From menu, Signal -> Rebin doesn't work

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#97]
As title. The x,y,z window appears, but clicking Rebin after specifying parameters doesn't do anything. The window remains where it is.

**Comment by vidartf** [comment]
Are there any errors in the log? The window should remain where it is, but the signal should naturally be rebinned (lower resolution). What happens if you try to replot the signal afterwards?

**Comment by thomasaarholt** [comment]
Sorry, should have included. It returns the same error both for line profiles and maps - it should not be checking the Signal2D object for the former.
```python
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/plugins/rebin.py", line 107, in rebin
    self.plugin.rebin(factors, self.signal)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/plugins/rebin.py", line 69, in rebin
    old = s.auto_replot
AttributeError: 'Signal2D' object has no attribute 'auto_replot'

```

**Comment by thomasaarholt** [comment]
As far as I can tell it does not compute the rebinned signal. There is no expected "delay" when I click rebin on a large signal.

**Comment by vidartf** [comment]
This should be fixed in master.

**Comment by vidartf** [comment]
#93 / bde15a7b8e17a60502d984430833d539b37f3a90

**Comment by thomasaarholt** [comment]
Ah, my fault. Didn't check if I had updated.

**Comment by vidartf** [comment]
Reopen if needed :)
