### ISSUE TITLE
Hyperspyui doesn't start 50% of the time

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#99]
Thought I'd report this one, which has been a semi-issue for a long time.
Approximately 50% of the time, hyperspyui doesn't start when I type `hyperspyui` in the terminal. It'll show:
```
Thomas-Macbook-Pro:~ thomas$ hyperspyui
INFO:hyperspy.io_plugins.bcf:The fast cython based bcf unpacking library were found
(hs) Thomas-Macbook-Pro:~ thomas$ 
```
Only tested this on Mac, so I'm unsure if this is present on other systems.

**Comment by thomasaarholt** [comment]
Right. Of course the day I decide to report it (because it came up twice in a row), hyperspyui refuses to start at all.
In the console I get 
`MacOS error: -67062`, which google tells me is "a bizarre error: it means that a code object involved is unsigned, and comes from macOS security checks."

There's more in the console, just pasting here in case people working on other software try to search.
```
default	11:33:54.499403 +0000	taskgated	MacOS error: -67062
default	11:33:54.757542 +0000	gamed	GKClientProxy: clientForBundleID:
default	11:33:54.757731 +0000	gamed	GKClientProxy: updateIfRecentlyInstalled
default	11:33:54.760390 +0000	gamed	GKClientProxy: clientForBundleID:
default	11:33:54.760755 +0000	gamed	GKClientProxy: updateIfRecentlyInstalled
default	11:33:54.789317 +0000	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	11:33:55.528125 +0000	python3.5	WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.2 instead of 10.12.2. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
default	11:33:55.528466 +0000	python3.5	0   CarbonCore                          0x00007fff76bb81e1 ___Gestalt_SystemVersion_block_invoke + 121
default	11:33:55.528523 +0000	python3.5	1   libdispatch.dylib                   0x00007fff8b2580b8 _dispatch_client_callout + 8
default	11:33:55.528574 +0000	python3.5	2   libdispatch.dylib                   0x00007fff8b258075 dispatch_once_f + 38
default	11:33:55.528646 +0000	python3.5	3   CarbonCore                          0x00007fff76b46272 _Gestalt_SystemVersion + 976
default	11:33:55.528697 +0000	python3.5	4   CarbonCore                          0x00007fff76b45a8d Gestalt + 139
default	11:33:55.528756 +0000	python3.5	5   libQtCore.4.8.7.dylib               0x00000001054ac11c _ZN16QSettingsPrivate6createEN9QSettings6FormatENS0_5ScopeERK7QStringS5_ + 70
default	11:33:55.528823 +0000	python3.5	6   libQtCore.4.8.7.dylib               0x00000001054890a8 _ZN9QSettingsC2EP7QObject + 86
```

**Comment by vidartf** [comment]
Is this related to the app you made maybe? Also, the default behavior is to only have a single instance of the UI running at the time. Maybe there is some special behavior on Mac that is not being taken into account?

**Comment by vidartf** [comment]
You could try to change the default behavior of single vs multi instance in the settings dialog.

**Comment by thomasaarholt** [comment]
Ahem. I figured out the reason it wasn't starting earlier. It was because it was already open. Felt too foolish to admit it.

That said, the behaviour of sometimes (~50%) not starting is real. The error above probably has nothing to do with it though. The bug is present if I just type `hyperspyui` as well, so nothing to do with the app.

**Comment by thomasaarholt** [comment]
That said, I'll try with the multi instance setting and see if that changes anything.

**Comment by vidartf** [comment]
Closing for now, reopen if you have any more data.
